esphome:
  name: moisture-sensor-name
  friendly_name: Moisture Name

esp32: 
  board: lolin_s2_mini 
  variant: esp32s2 
  framework: 
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
  
# WIFI Credentials
wifi:
  ssid: "esp_session"
  password: "esp12345"
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
web_server:
