name: ESPHome Compile

on:
  push:
    paths:
      - 'config/**'  # Trigger on changes in the config directory
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile ESPHome Configuration
        uses: esphome/build-action@v6
        with:
          yaml-file: config/moisture_sensor.yaml

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build_output/*.bin
