name: ESPHome Compile

on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ESPHome Builder - Compile
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: config/moisture_sensor.yaml
          complete-manifest: true

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: moisture-sensor-francisco-esp32s2/*.bin  # Collect both .factory.bin and .ota.bin files from the output directory

      - name: Upload Manifest File (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: manifest
          path: moisture-sensor-francisco-esp32s2/manifest.json  # Upload the manifest file if needed
